Feature: Manage conference_grants
  In order to [goal]
  [stakeholder]
  wants [behaviour]

  Scenario: Register new conference_grant
    Given I am on the new conference_grant page
    When I fill in "Name" with "name 1"
    And I fill in "Staff" with "staff_id 1"
    And I fill in "Passport" with "passport_id 1"
    And I fill in "Post" with "post 1"
    And I fill in "Years at iiis" with "1"
    And I fill in "Phone num" with "phone_num 1"
    And I fill in "Conf name" with "conf_name 1"
    #And I fill in "Conf date" with "conf_date 1"
    And I fill in "Conf place" with "conf_place 1"
    And I uncheck "Present paper"
    And I uncheck "Present poster"
    And I fill in "Title1" with "title1 1"
    And I fill in "Title2" with "title2 1"
    And I fill in "Title3" with "title3 1"
    And I fill in "Title4" with "title4 1"
    And I uncheck "Coauthored"
    And I fill in "Coauthor type" with "coauthor_type 1"
    And I uncheck "Coauthor present"
    And I fill in "Airfare" with "1.5"
    And I fill in "Reg fee" with "2.5"
    And I fill in "Hotel fare" with "3.5"
    And I fill in "Other fare" with "4.5"
    And I fill in "Other fare descr" with "other_fare_descr 1"
    #And I fill in "Last approval date" with "last_approval_date 1"
    And I uncheck "Host fund airfare"
    And I uncheck "Host fund hotel"
    And I uncheck "Host fund honorarium"
    And I uncheck "Host fund others"
    And I fill in "Host fund others descr" with "host_fund_others_descr 1"
    And I uncheck "Other fund airfare"
    And I uncheck "Other fund hotel"
    And I uncheck "Other fund honorarium"
    And I uncheck "Other fund others"
    And I fill in "Other fund others descr" with "other_fund_others_descr 1"
    And I fill in "Leave application" with "1"
    And I press "Create"
    Then I should see "name 1"
    And I should see "staff_id 1"
    And I should see "passport_id 1"
    And I should see "post 1"
    And I should see "1"
    And I should see "phone_num 1"
    And I should see "conf_name 1"
    #And I should see "conf_date 1"
    And I should see "conf_place 1"
    And I should see "false"
    And I should see "false"
    And I should see "title1 1"
    And I should see "title2 1"
    And I should see "title3 1"
    And I should see "title4 1"
    And I should see "false"
    And I should see "coauthor_type 1"
    And I should see "false"
    And I should see "1.5"
    And I should see "2.5"
    And I should see "3.5"
    And I should see "4.5"
    And I should see "other_fare_descr 1"
    #And I should see "last_approval_date 1"
    And I should see "false"
    And I should see "false"
    And I should see "false"
    And I should see "false"
    And I should see "host_fund_others_descr 1"
    And I should see "false"
    And I should see "false"
    And I should see "false"
    And I should see "false"
    And I should see "other_fund_others_descr 1"
    And I should see "1"

  Scenario: Update new conference_grant
    Given the following conference_grants:
      |name|staff_id|passport_id|post|years_at_iiis|phone_num|conf_name|conf_date|conf_place|present_paper|present_poster|title1|title2|title3|title4|coauthored|coauthor_type|coauthor_present|airfare|reg_fee|hotel_fare|other_fare|other_fare_descr|last_approval_date|host_fund_airfare|host_fund_hotel|host_fund_honorarium|host_fund_others|host_fund_others_descr|other_fund_airfare|other_fund_hotel|other_fund_honorarium|other_fund_others|other_fund_others_descr|leave_application_id|
      |name 1|staff_id 1|passport_id 1|post 1|1|phone_num 1|conf_name 1|conf_date 1|conf_place 1|false|false|title1 1|title2 1|title3 1|title4 1|false|coauthor_type 1|false|1.5|2.5|3.5|4.5|other_fare_descr 1|last_approval_date 1|false|false|false|false|host_fund_others_descr 1|false|false|false|false|other_fund_others_descr 1|1|
      |name 2|staff_id 2|passport_id 2|post 2|2|phone_num 2|conf_name 2|conf_date 2|conf_place 2|true|true|title1 2|title2 2|title3 2|title4 2|true|coauthor_type 2|true|airfare 2|reg_fee 2|hotel_fare 2|other_fare 2|other_fare_descr 2|last_approval_date 2|true|true|true|true|host_fund_others_descr 2|true|true|true|true|other_fund_others_descr 2|2|
      |name 3|staff_id 3|passport_id 3|post 3|3|phone_num 3|conf_name 3|conf_date 3|conf_place 3|false|false|title1 3|title2 3|title3 3|title4 3|false|coauthor_type 3|false|airfare 3|reg_fee 3|hotel_fare 3|other_fare 3|other_fare_descr 3|last_approval_date 3|false|false|false|false|host_fund_others_descr 3|false|false|false|false|other_fund_others_descr 3|3|
      |name 4|staff_id 4|passport_id 4|post 4|4|phone_num 4|conf_name 4|conf_date 4|conf_place 4|true|true|title1 4|title2 4|title3 4|title4 4|true|coauthor_type 4|true|airfare 4|reg_fee 4|hotel_fare 4|other_fare 4|other_fare_descr 4|last_approval_date 4|true|true|true|true|host_fund_others_descr 4|true|true|true|true|other_fund_others_descr 4|4|
    And I am on the edit conference_grant 1 page
    When I fill in "Name" with "name 1"
    And I fill in "Staff" with "staff_id 1"
    And I fill in "Passport" with "passport_id 1"
    And I fill in "Post" with "post 1"
    And I fill in "Years at iiis" with "1"
    And I fill in "Phone num" with "phone_num 1"
    And I fill in "Conf name" with "conf_name 1"
    #And I fill in "Conf date" with "conf_date 1"
    And I fill in "Conf place" with "conf_place 1"
    And I uncheck "Present paper"
    And I uncheck "Present poster"
    And I fill in "Title1" with "title1 1"
    And I fill in "Title2" with "title2 1"
    And I fill in "Title3" with "title3 1"
    And I fill in "Title4" with "title4 1"
    And I uncheck "Coauthored"
    And I fill in "Coauthor type" with "coauthor_type 1"
    And I uncheck "Coauthor present"
    And I fill in "Airfare" with "1.5"
    And I fill in "Reg fee" with "2.5"
    And I fill in "Hotel fare" with "3.5"
    And I fill in "Other fare" with "4.5"
    And I fill in "Other fare descr" with "other_fare_descr 1"
    #And I fill in "Last approval date" with "last_approval_date 1"
    And I uncheck "Host fund airfare"
    And I uncheck "Host fund hotel"
    And I uncheck "Host fund honorarium"
    And I uncheck "Host fund others"
    And I fill in "Host fund others descr" with "host_fund_others_descr 1"
    And I uncheck "Other fund airfare"
    And I uncheck "Other fund hotel"
    And I uncheck "Other fund honorarium"
    And I uncheck "Other fund others"
    And I fill in "Other fund others descr" with "other_fund_others_descr 1"
    And I fill in "Leave application" with "1"
    And I press "Update"
    Then I should see "name 1"
    And I should see "staff_id 1"
    And I should see "passport_id 1"
    And I should see "post 1"
    And I should see "1"
    And I should see "phone_num 1"
    And I should see "conf_name 1"
    #And I should see "conf_date 1"
    And I should see "conf_place 1"
    And I should see "false"
    And I should see "false"
    And I should see "title1 1"
    And I should see "title2 1"
    And I should see "title3 1"
    And I should see "title4 1"
    And I should see "false"
    And I should see "coauthor_type 1"
    And I should see "false"
    And I should see "1.5"
    And I should see "2.5"
    And I should see "3.5"
    And I should see "4.5"
    And I should see "other_fare_descr 1"
    #And I should see "last_approval_date 1"
    And I should see "false"
    And I should see "false"
    And I should see "false"
    And I should see "false"
    And I should see "host_fund_others_descr 1"
    And I should see "false"
    And I should see "false"
    And I should see "false"
    And I should see "false"
    And I should see "other_fund_others_descr 1"
    And I should see "1"

  Scenario: Delete conference_grant
    Given the following conference_grants:
      |name|staff_id|passport_id|post|years_at_iiis|phone_num|conf_name|conf_date|conf_place|present_paper|present_poster|title1|title2|title3|title4|coauthored|coauthor_type|coauthor_present|airfare|reg_fee|hotel_fare|other_fare|other_fare_descr|last_approval_date|host_fund_airfare|host_fund_hotel|host_fund_honorarium|host_fund_others|host_fund_others_descr|other_fund_airfare|other_fund_hotel|other_fund_honorarium|other_fund_others|other_fund_others_descr|leave_application_id|
      |name 1|staff_id 1|passport_id 1|post 1|1|phone_num 1|conf_name 1|conf_date 1|conf_place 1|false|false|title1 1|title2 1|title3 1|title4 1|false|coauthor_type 1|false|1.5|2.5|3.5|4.5|other_fare_descr 1|last_approval_date 1|false|false|false|false|host_fund_others_descr 1|false|false|false|false|other_fund_others_descr 1|1|
      |name 2|staff_id 2|passport_id 2|post 2|2|phone_num 2|conf_name 2|conf_date 2|conf_place 2|true|true|title1 2|title2 2|title3 2|title4 2|true|coauthor_type 2|true|airfare 2|reg_fee 2|hotel_fare 2|other_fare 2|other_fare_descr 2|last_approval_date 2|true|true|true|true|host_fund_others_descr 2|true|true|true|true|other_fund_others_descr 2|2|
      |name 3|staff_id 3|passport_id 3|post 3|3|phone_num 3|conf_name 3|conf_date 3|conf_place 3|false|false|title1 3|title2 3|title3 3|title4 3|false|coauthor_type 3|false|airfare 3|reg_fee 3|hotel_fare 3|other_fare 3|other_fare_descr 3|last_approval_date 3|false|false|false|false|host_fund_others_descr 3|false|false|false|false|other_fund_others_descr 3|3|
      |name 4|staff_id 4|passport_id 4|post 4|4|phone_num 4|conf_name 4|conf_date 4|conf_place 4|true|true|title1 4|title2 4|title3 4|title4 4|true|coauthor_type 4|true|airfare 4|reg_fee 4|hotel_fare 4|other_fare 4|other_fare_descr 4|last_approval_date 4|true|true|true|true|host_fund_others_descr 4|true|true|true|true|other_fund_others_descr 4|4|
    When I delete the 3rd conference_grant
    Then I should see the following conference_grants:
      |Name|Staff|Passport|Post|Years at iiis|Phone num|Conf name|Conf date|Conf place|Present paper|Present poster|Title1|Title2|Title3|Title4|Coauthored|Coauthor type|Coauthor present|Airfare|Reg fee|Hotel fare|Other fare|Other fare descr|Last approval date|Host fund airfare|Host fund hotel|Host fund honorarium|Host fund others|Host fund others descr|Other fund airfare|Other fund hotel|Other fund honorarium|Other fund others|Other fund others descr|Leave application|
      |name 1|staff_id 1|passport_id 1|post 1|1|phone_num 1|conf_name 1|conf_date 1|conf_place 1|false|false|title1 1|title2 1|title3 1|title4 1|false|coauthor_type 1|false|1.5|2.5|3.5|4.5|other_fare_descr 1|last_approval_date 1|false|false|false|false|host_fund_others_descr 1|false|false|false|false|other_fund_others_descr 1|1|
      |name 2|staff_id 2|passport_id 2|post 2|2|phone_num 2|conf_name 2|conf_date 2|conf_place 2|true|true|title1 2|title2 2|title3 2|title4 2|true|coauthor_type 2|true|airfare 2|reg_fee 2|hotel_fare 2|other_fare 2|other_fare_descr 2|last_approval_date 2|true|true|true|true|host_fund_others_descr 2|true|true|true|true|other_fund_others_descr 2|2|
      |name 4|staff_id 4|passport_id 4|post 4|4|phone_num 4|conf_name 4|conf_date 4|conf_place 4|true|true|title1 4|title2 4|title3 4|title4 4|true|coauthor_type 4|true|airfare 4|reg_fee 4|hotel_fare 4|other_fare 4|other_fare_descr 4|last_approval_date 4|true|true|true|true|host_fund_others_descr 4|true|true|true|true|other_fund_others_descr 4|4|
