require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConferenceGrantsController do

  # This should return the minimal set of attributes required to create a valid
  # ConferenceGrant. As you add validations to ConferenceGrant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConferenceGrantsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all conference_grants as @conference_grants" do
      conference_grant = ConferenceGrant.create! valid_attributes
      get :index, {}, valid_session
      assigns(:conference_grants).should eq([conference_grant])
    end
  end

  describe "GET show" do
    it "assigns the requested conference_grant as @conference_grant" do
      conference_grant = ConferenceGrant.create! valid_attributes
      get :show, {:id => conference_grant.to_param}, valid_session
      assigns(:conference_grant).should eq(conference_grant)
    end
  end

  describe "GET new" do
    it "assigns a new conference_grant as @conference_grant" do
      get :new, {}, valid_session
      assigns(:conference_grant).should be_a_new(ConferenceGrant)
    end
  end

  describe "GET edit" do
    it "assigns the requested conference_grant as @conference_grant" do
      conference_grant = ConferenceGrant.create! valid_attributes
      get :edit, {:id => conference_grant.to_param}, valid_session
      assigns(:conference_grant).should eq(conference_grant)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ConferenceGrant" do
        expect {
          post :create, {:conference_grant => valid_attributes}, valid_session
        }.to change(ConferenceGrant, :count).by(1)
      end

      it "assigns a newly created conference_grant as @conference_grant" do
        post :create, {:conference_grant => valid_attributes}, valid_session
        assigns(:conference_grant).should be_a(ConferenceGrant)
        assigns(:conference_grant).should be_persisted
      end

      it "redirects to the created conference_grant" do
        post :create, {:conference_grant => valid_attributes}, valid_session
        response.should redirect_to(ConferenceGrant.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved conference_grant as @conference_grant" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConferenceGrant.any_instance.stub(:save).and_return(false)
        post :create, {:conference_grant => { "name" => "invalid value" }}, valid_session
        assigns(:conference_grant).should be_a_new(ConferenceGrant)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConferenceGrant.any_instance.stub(:save).and_return(false)
        post :create, {:conference_grant => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested conference_grant" do
        conference_grant = ConferenceGrant.create! valid_attributes
        # Assuming there are no other conference_grants in the database, this
        # specifies that the ConferenceGrant created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ConferenceGrant.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => conference_grant.to_param, :conference_grant => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested conference_grant as @conference_grant" do
        conference_grant = ConferenceGrant.create! valid_attributes
        put :update, {:id => conference_grant.to_param, :conference_grant => valid_attributes}, valid_session
        assigns(:conference_grant).should eq(conference_grant)
      end

      it "redirects to the conference_grant" do
        conference_grant = ConferenceGrant.create! valid_attributes
        put :update, {:id => conference_grant.to_param, :conference_grant => valid_attributes}, valid_session
        response.should redirect_to(conference_grant)
      end
    end

    describe "with invalid params" do
      it "assigns the conference_grant as @conference_grant" do
        conference_grant = ConferenceGrant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConferenceGrant.any_instance.stub(:save).and_return(false)
        put :update, {:id => conference_grant.to_param, :conference_grant => { "name" => "invalid value" }}, valid_session
        assigns(:conference_grant).should eq(conference_grant)
      end

      it "re-renders the 'edit' template" do
        conference_grant = ConferenceGrant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConferenceGrant.any_instance.stub(:save).and_return(false)
        put :update, {:id => conference_grant.to_param, :conference_grant => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested conference_grant" do
      conference_grant = ConferenceGrant.create! valid_attributes
      expect {
        delete :destroy, {:id => conference_grant.to_param}, valid_session
      }.to change(ConferenceGrant, :count).by(-1)
    end

    it "redirects to the conference_grants list" do
      conference_grant = ConferenceGrant.create! valid_attributes
      delete :destroy, {:id => conference_grant.to_param}, valid_session
      response.should redirect_to(conference_grants_url)
    end
  end

end
