require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VisitorInvitationsController do

  # This should return the minimal set of attributes required to create a valid
  # VisitorInvitation. As you add validations to VisitorInvitation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "Name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VisitorInvitationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all visitor_invitations as @visitor_invitations" do
      visitor_invitation = VisitorInvitation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:visitor_invitations).should eq([visitor_invitation])
    end
  end

  describe "GET show" do
    it "assigns the requested visitor_invitation as @visitor_invitation" do
      visitor_invitation = VisitorInvitation.create! valid_attributes
      get :show, {:id => visitor_invitation.to_param}, valid_session
      assigns(:visitor_invitation).should eq(visitor_invitation)
    end
  end

  describe "GET new" do
    it "assigns a new visitor_invitation as @visitor_invitation" do
      get :new, {}, valid_session
      assigns(:visitor_invitation).should be_a_new(VisitorInvitation)
    end
  end

  describe "GET edit" do
    it "assigns the requested visitor_invitation as @visitor_invitation" do
      visitor_invitation = VisitorInvitation.create! valid_attributes
      get :edit, {:id => visitor_invitation.to_param}, valid_session
      assigns(:visitor_invitation).should eq(visitor_invitation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VisitorInvitation" do
        expect {
          post :create, {:visitor_invitation => valid_attributes}, valid_session
        }.to change(VisitorInvitation, :count).by(1)
      end

      it "assigns a newly created visitor_invitation as @visitor_invitation" do
        post :create, {:visitor_invitation => valid_attributes}, valid_session
        assigns(:visitor_invitation).should be_a(VisitorInvitation)
        assigns(:visitor_invitation).should be_persisted
      end

      it "redirects to the created visitor_invitation" do
        post :create, {:visitor_invitation => valid_attributes}, valid_session
        response.should redirect_to(VisitorInvitation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved visitor_invitation as @visitor_invitation" do
        # Trigger the behavior that occurs when invalid params are submitted
        VisitorInvitation.any_instance.stub(:save).and_return(false)
        post :create, {:visitor_invitation => { "Name" => "invalid value" }}, valid_session
        assigns(:visitor_invitation).should be_a_new(VisitorInvitation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VisitorInvitation.any_instance.stub(:save).and_return(false)
        post :create, {:visitor_invitation => { "Name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested visitor_invitation" do
        visitor_invitation = VisitorInvitation.create! valid_attributes
        # Assuming there are no other visitor_invitations in the database, this
        # specifies that the VisitorInvitation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VisitorInvitation.any_instance.should_receive(:update_attributes).with({ "Name" => "MyString" })
        put :update, {:id => visitor_invitation.to_param, :visitor_invitation => { "Name" => "MyString" }}, valid_session
      end

      it "assigns the requested visitor_invitation as @visitor_invitation" do
        visitor_invitation = VisitorInvitation.create! valid_attributes
        put :update, {:id => visitor_invitation.to_param, :visitor_invitation => valid_attributes}, valid_session
        assigns(:visitor_invitation).should eq(visitor_invitation)
      end

      it "redirects to the visitor_invitation" do
        visitor_invitation = VisitorInvitation.create! valid_attributes
        put :update, {:id => visitor_invitation.to_param, :visitor_invitation => valid_attributes}, valid_session
        response.should redirect_to(visitor_invitation)
      end
    end

    describe "with invalid params" do
      it "assigns the visitor_invitation as @visitor_invitation" do
        visitor_invitation = VisitorInvitation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VisitorInvitation.any_instance.stub(:save).and_return(false)
        put :update, {:id => visitor_invitation.to_param, :visitor_invitation => { "Name" => "invalid value" }}, valid_session
        assigns(:visitor_invitation).should eq(visitor_invitation)
      end

      it "re-renders the 'edit' template" do
        visitor_invitation = VisitorInvitation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VisitorInvitation.any_instance.stub(:save).and_return(false)
        put :update, {:id => visitor_invitation.to_param, :visitor_invitation => { "Name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested visitor_invitation" do
      visitor_invitation = VisitorInvitation.create! valid_attributes
      expect {
        delete :destroy, {:id => visitor_invitation.to_param}, valid_session
      }.to change(VisitorInvitation, :count).by(-1)
    end

    it "redirects to the visitor_invitations list" do
      visitor_invitation = VisitorInvitation.create! valid_attributes
      delete :destroy, {:id => visitor_invitation.to_param}, valid_session
      response.should redirect_to(visitor_invitations_url)
    end
  end

end
